spring.application.name=Room911
spring.datasource.url=jdbc:postgresql://localhost:5432/Sala_911
spring.datasource.username=postgres
spring.datasource.password=fabrica2024*

# DDL y Scripts de Inicialización
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always
spring.sql.init.continue-on-error=true
spring.jpa.defer-datasource-initialization=true

# Logs de SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
